# Generated by Django 6.0.3 on 2026-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "пользователь", "verbose_name_plural": "пользователи"},
        ),
    ]
