# Generated by Django 6.0.3 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_options_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="номер телефона"),
        ),
    ]
