# Generated by Django 6.0.3 on 2026-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/image/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("publication", models.BooleanField(verbose_name="признак публикации")),
                ("show_counted", models.PositiveIntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "db_table": "blog",
            },
        ),
    ]
