# Generated by Django 6.0.3 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="признак публикации"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="show_counted",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
