# Generated by Django 6.0.3 on 2026-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_publication_alter_blog_show_counted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publication",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="признак публикации"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="show_counted",
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Количество просмотров"),
        ),
    ]
