# Generated by Django 6.0.3 on 2026-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_created_at_alter_blog_publication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Дата создания"),
        ),
    ]
