# Generated by Django 6.0.3 on 2026-04-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["id"], "verbose_name": "блог", "verbose_name_plural": "блоги"},
        ),
    ]
