# Generated by Django 6.0.3 on 2026-04-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории товара",
                        max_length=100,
                        verbose_name="наименование категории товара",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание категории товара")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование товара", max_length=100, verbose_name="наименование товара"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание товара")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="image/", verbose_name="изображение товара"),
                ),
                ("price", models.FloatField(blank=True, null=True, verbose_name="цена товара")),
                ("created_at", models.DateField(auto_now_add=True, null=True, verbose_name="дата создания товара")),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="дата последнего изменения товара"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Введите категорию товара",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
    ]
