# Generated by Django 6.0.3 on 2026-04-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
