# Generated by Django 6.0.3 on 2026-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"], "verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"], "verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
    ]
