# Generated by Django 6.0.3 on 2026-04-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_contact_alter_product_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
