# Generated by Django 6.0.3 on 2026-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=50, verbose_name="страна")),
                ("number", models.TextField(verbose_name="номер телефона")),
                ("adress", models.CharField(max_length=100, verbose_name="адрес")),
            ],
            options={
                "verbose_name": "контакты",
                "db_table": "contact",
            },
        ),
    ]
