# Generated by Django 6.0.3 on 2026-04-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "контакты", "verbose_name_plural": "контакты"},
        ),
    ]
