# Generated by Django 6.0.3 on 2026-04-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_contact_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
