# Generated by Django 6.0.3 on 2026-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="название компании")),
                ("email", models.TextField(verbose_name="почта")),
                ("number", models.TextField(verbose_name="номер телефона")),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
                "db_table": "contact",
            },
        ),
    ]
