# Generated by Django 6.0.3 on 2026-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание товара", null=True, verbose_name="описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Введите цену товара",
                max_digits=20,
                null=True,
                verbose_name="цена товара",
            ),
        ),
    ]
