# Generated by Django 6.0.3 on 2026-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_description_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Введите цену товара",
                max_digits=20,
                null=True,
                verbose_name="цена товара",
            ),
        ),
    ]
