# Generated by Django 6.0.3 on 2026-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False, verbose_name="статус публикации"),
        ),
    ]
