# Generated by Django 6.0.3 on 2026-05-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
