# Generated by Django 6.0.3 on 2026-05-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
    ]
